name: hank
description: Dart implementation of the Hank language.
version: 1.3.0
homepage: https://igazine.github.io/hank/
repository: https://github.com/Igazine/hank-dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.9.0
